const productos = [
    { id: 1,
        nombre: "Helecho",
        imagen: "images/helecho1.jpg",
        descripcion: "Una planta muy purificadora y de fácil cultivo.",
        precio: 7,
        stock: 3 },
    { id: 2,
        nombre: "Pernetia",
        imagen: "images/pernetia.jpg",
        descripcion: "Un arbusto perene de pequeñas hojas y bayas comestibles de color blanco, rojo y rosa.",
        precio: 9,
        stock: 6 },
    { id: 3,
        nombre: "Brezo de otoño",
        imagen: "images/ericagracilis1.jpg",
        descripcion: "Una de las plantas preferidas para decorar en otoño, aportando un toque rústico o silvestre.",
        precio: 5,
        stock: 3 },
    { id: 4,
        nombre: "Dionaea Muscipula",
        imagen: "images/dionaeamuscipula.webp",
        descripcion: "Comúnmente conocida como Venus atrapamoscas, es una planta carnívora originaria de América que cautiva con su singular mecanismo de captura.",
        precio: 6,
        stock: 4 },
    { id: 5,
        nombre: "Orquídea Phalaenopsis",
        imagen: "images/orquidea1.webp",
        descripcion: "Una orquídea de preciosas y elegantes flores blancas, que además de transmitir delicadeza, aportarán elegancia y belleza en estado puro.",
        precio: 18,
        stock: 6 },        
    { id: 6,
        nombre: "Aloe Vera",
        imagen: "images/aloevera.webp",
        descripcion: "Ampliamente conocido por sus propiedades medicinales y su fácil cuidado, haciéndolo un favorito en hogares de todo el mundo.",
        precio: 6,
        stock: 6 },
    { id: 7,
        nombre: "Aspidistra",
        imagen: "images/aspidistra1.webp",
        descripcion: "También conocida como pilistra, hojalata u oreja de burro, es una planta de interior excepcionalmente resistente, apreciada por su capacidad para prosperar en condiciones donde muchas otras plantas fallarían.",
        precio: 20,
        stock: 1 },
    { id: 8,
        nombre: "Hierba gatera",
        imagen: "images/hierbagatera1.webp",
        descripcion: "Una hierba o gramínea ideal para gatos que sirve de purgante natural para los felinos.",
        precio: 3,
        stock: 2 },
    { id: 9,
        nombre: "Monstera deliciosa",
        imagen: "images/monstera1.jpg",
        descripcion: "Se caracteriza por poseer unas hojas de color verde de gran tamaño y un tallo grueso, que requiere de un soporte si se quiere mantener erguida.",
        precio: 13,
        stock: 8 },        
    { id: 10,
        nombre: "Bonsai Carmona",
        imagen: "images/bonsaicarmona.jpg",
        descripcion: "Posee una hoja de tipo perenne y se trata de uno de los bonsáis más fáciles de cuidar y es ideal para comenzar a practicar este arte milenario.",
        precio: 65,
        stock: 4 },
    { id: 11,
        nombre: "Yucca Gigantea",
        imagen: "images/yuccagigantea1.webp",
        descripcion: "Una planta perenne, con hojas en forma de roseta, alargadas y puntiagudas, de color verde. En las condiciones adecuadas, tiene unas flores blancas en forma de campana.",
        precio: 80,
        stock: 3 },
    { id: 12,
        nombre: "Hiedra colgante",
        imagen: "images/hiedracolgante.webp",
        descripcion: "Una planta perfecta para añadir un toque de elegancia a cualquier espacio.",
        precio: 8,
        stock: 8 },
    { id: 13,
        nombre: "Árbol de jade",
        imagen: "images/arboljade1.jpg",
        descripcion: "Una de las plantas de interior más fáciles de cuidar.",
        precio: 5,
        stock: 5 },
    { id: 14,
        nombre: "Hortensia de interior",
        imagen: "images/hortensiainterior.webp",
        descripcion: "Un arbusto de porte compacto y redondeado, con un gran abanico de colores que dependerán de su variedad.",
        precio: 22,
        stock: 8 },
  ];
